### ISSUE TITLE
Subscribe and Edit Subscription links?

### ISSUE THREAD

**Issue by barmstrong** [rlivsey/rspreedly#1]
Great plugin!  Thanks for posting it.

These are much easier than the part you've implemented, but did you include a way to generate a subscribe link and edit subscription link?

**Comment by rlivsey** [comment]
I haven't no, that's a good point though.

I'll take a look at that asap (pretty busy today, but should have time tomorrow) or feel free to fork and issue a pull request.

Thanks.

**Comment by macmartine** [comment]
I just checked these methods into my clone and made a pull request for them to get added here too.

**Comment by rlivsey** [comment]
Thanks, have pulled the changes and released version 0.1.17.

Very useful, I had a few helpers doing the same thing in my apps, but makes much more sense for the subscriber to know about them.

Cheers.
