### ISSUE TITLE
Could you please package a new gem with the latest bugfixes?

### ISSUE THREAD

**Issue by nfm** [rlivsey/rspreedly#13]
I'd love it if you could release a gem for the current state of master (`99bce7a10ca0463ed047`) containing pull requests #9, #10, and #11.

I'm using the payments API and am relying on these bugfixes, but I'd rather source the gem from rubygems rather than from github if possible.

Thanks for a great gem, I'm loving the AR style syntax.

**Comment by rlivsey** [comment]
No problem, just bumped version to 0.1.16 & pushed to rubygems

Cheers!
