### ISSUE TITLE
Where should the rspreedly config go in Rails?

### ISSUE THREAD

**Issue by dgmstuart** [rlivsey/rspreedly#16]
Apologies for the n00bness of my question, but where should I add the `RSpreedly::Config.setup` lines in my rails app? A line in the readme would be much appreciated.

**Comment by rlivsey** [comment]
Hi, you can add an initializer to config/initializers/, or in your environment files if your config differs per env, so config/environments/development.rb etc...

**Comment by dgmstuart** [comment]
Awesome - thanks so much for your speedy response
