### ISSUE TITLE
Add Transactions and something extra

### ISSUE THREAD

**Issue by spockz** [rlivsey/rspreedly#3]
Maybe it's handy to add a Transaction class to lookup transactions? And probably a find for Invoices would be nice, if there is an API for that.

If I hear back from spreedly about the latter I'm willing to add it myself and do a fork request.

Did you find out whether the ActiveResource method is available for all their `resources'? (https://spreedly.com/manual/integration-reference/api-access-using-rails/)

**Comment by rlivsey** [comment]
There's now a Transaction model and the Subscriber model supports invoices.

I've not looked at ActiveResource as I originally wanted to keep it separate from Rails (I was mainly using Merb back then). Might take a 2nd look at some point though.
