### ISSUE TITLE
"Payment Account on File" functionality

### ISSUE THREAD

**Issue by kevinansfield** [rlivsey/rspreedly#5]
The Spreedly API now allows for paying invoices using payment details that are kept on file by Spreedly. In order for RSpreedly to support this there are two updates required:
1. Retrieval of the "payment_account_on_file" boolean for subscriptions
2. PaymentMethod allowing for the "on-file" payment method- See the Extra Credit section here: http://spreedly.com/manual/integration-reference/payments-api/pay-invoice/

I'll be having a look at this myself at some point but thought I'd make an issue for it now in case others have tackled the problem or looking for more information.

**Comment by rlivsey** [comment]
I've merged your pull request in (finally), thanks for that
